const express = require('express')
const cors = require('cors')
const app = express()
app.use(cors({credentials: true, origin: 'http://localhost:3000'}))
app.use(express.json())
app.use(express.urlencoded({extended: true}))
require('./config/mongoose.config')
require('./routes/user.routes')(app)
require('dotenv').config()
const cookieParser = require('cookie-parser')
app.use(cookieParser())
app.listen(8000, () => console.log("The server is doing it's thang on port 8000"))